local create_queue = require("queue")

test("queue pushright/popleft", function()
    local q = create_queue()
    q:pushright("a")
    q:pushright("b")
    assert_eq(q:popleft(), "a")
    assert_eq(q:popleft(), "b")
    assert_true(q:empty())
end)

test("queue pushleft/popright", function()
    local q = create_queue()
    q:pushleft("a")
    q:pushleft("b")
    assert_eq(q:popright(), "a")
    assert_eq(q:popright(), "b")
    assert_true(q:empty())
end)

test("queue peek and size", function()
    local q = create_queue()
    q:pushright(1)
    q:pushright(2)
    assert_eq(q:peekleft(), 1)
    assert_eq(q:peekright(), 2)
    assert_eq(q:size(), 2)
end)

test("queue clear", function()
    local q = create_queue()
    q:pushright(1)
    q:pushright(2)
    q:pushright(3)
    q:clear()
    assert_true(q:empty())
    assert_eq(q:size(), 0)
end)

test("queue get and getrange", function()
    local q = create_queue()
    q:pushright("x")
    q:pushright("y")
    local l, r = q:getrange()
    assert_eq(l, 0)
    assert_eq(r, 1)
    assert_eq(q:get(0), "x")
    assert_eq(q:get(1), "y")
    assert_eq(q:get(-1), nil)
end)
